# ---------- Base Image ----------
FROM node:18-alpine

# ---------- Set working directory ----------
WORKDIR /app

# ---------- Install dependencies ----------
COPY package*.json ./
RUN npm install --production

# ---------- Copy source ----------
COPY . .

# ---------- Expose API port ----------
EXPOSE 4000

# ---------- Start application ----------
CMD ["npm", "run", "dev"]
